// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "new-york": {
    "select-with-search": {
      name: "select-with-search",
      type: "registry:ui",
      registryDependencies: ["button","command","popover"],
      files: ["registry/new-york/ui/select-with-search.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/select-with-search.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/new-york/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/new-york/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },  "default": {
    "select-with-search": {
      name: "select-with-search",
      type: "registry:ui",
      registryDependencies: ["button","command","popover"],
      files: ["registry/default/ui/select-with-search.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/select-with-search.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
